version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "11:30"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: "11:30"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  assignees:
  - nikkoura
